### PR TITLE
Database Change!

### PR DESCRIPTION
**Pull request by Guergeiro**
### API
- Swapped all API get requests, that used to use `SELECT` queries to fetch objects, to use database functions.
- Renamed `datas.py` to `datasconsumo.py`.
- Fixed all database related objects to lowercase, since the database is case insensitive (for objects only; values can have both).

### Database
- Changed all database objects to lowercase only.
- Changed how database relations work. A new database can be found below.

database

### CODE REVIEW

**Review by diogofalken — CHANGES_REQUESTED** [review]
Since you made changes to the datas.py file you need to change the blueprint and the import in the app.py file.

You need to change:
File app.py:
`from data import data`
`app.register_blueprint(datasementa)`

File datasementa.py:
`datas = Blueprint('datasementa', __name__)
`

**Comment by Guergeiro** [comment]
Fixed.

**Review by diogofalken — CHANGES_REQUESTED** [review]
You still need to change the data variable in datasementa.py in order for the module to be recognized in app.py.

`data = Blueprint('datasementa', __name__)`
`@data.route('/api/datasementa', methods=['GET'])`

Should be changed to:

`datasementas = Blueprint('datasementa', __name__) `
`@datasementas.route('/api/datasementa', methods=['GET'])`

**Review by diogofalken — APPROVED** [review]
Everything working fine now!
Good job, keep it up!

**Pull request merged**
