### PR TITLE
Added database tables and changed file structure

### PR DESCRIPTION
**Pull request by Guergeiro**
Added scripts to create database tables (missing relations between tables).
Changed file structure to separate web, api and database.

### CODE REVIEW

**Comment by diogofalken** [comment]
What do you think about changing all the primary keys to snake case?

It would be something like **cod_consumo** instead of **cod_Consumo**.

**Comment by Guergeiro** [comment]
I believe it's not necessary since the point was keeping the same format as the table name but, in singular form and not plural. This behavior repeats in all tables.

**Comment by diogofalken** [comment]
Was just a way to use a standard naming convention, but I see your point!

**Review by diogofalken — APPROVED** [review]

**Comment by Guergeiro** [comment]
The table names are not standardized as well. I don't believe it's a necessity.

**Comment by Guergeiro** [comment]
I will assume you tested the scripts and they are okay. Will merge now.

**Pull request merged**
